### PR TITLE
Autograd support and Model performance enhancements

### PR DESCRIPTION
**Pull request by richardotis**

### CODE REVIEW

**Comment by richardotis** [comment]
@mattjj Any ideas why my Windows CI build on AppVeyor might complain when it tries to install autograd? (Why it's trying to install autograd is another question; the build script should already have it conda install'd.) Reference: https://ci.appveyor.com/project/richardotis/pycalphad/build/feature_autograd.19/job/sg9uttx0ukm90pfj

```
[00:03:07] Searching for autograd
[00:03:07] Reading https://pypi.python.org/simple/autograd/
[00:03:07] Best match: autograd 1.1.1
[00:03:07] Downloading https://pypi.python.org/packages/source/a/autograd/autograd-1.1.1.tar.gz#md5=0277ce7102ecbd4bea760cf983c2985c
[00:03:08] Processing autograd-1.1.1.tar.gz
[00:03:08] Writing c:\users\appveyor\appdata\local\temp\1\easy_install-q09dn_\autograd-1.1.1\setup.cfg
[00:03:08] Running autograd-1.1.1\setup.py -q bdist_egg --dist-dir c:\users\appveyor\appdata\local\temp\1\easy_install-q09dn_\autograd-1.1.1\egg-dist-tmp-tlcrif
[00:03:08] Traceback (most recent call last):
[00:03:08]   File "setup.py", line 52, in <module>
[00:03:08]     'Programming Language :: Python :: 3.4'
[00:03:08]   File "C:\Python27-conda32\lib\distutils\core.py", line 151, in setup
[00:03:08]     dist.run_commands()
[00:03:08]   File "C:\Python27-conda32\lib\distutils\dist.py", line 953, in run_commands
[00:03:08]     self.run_command(cmd)
[00:03:08]   File "C:\Python27-conda32\lib\distutils\dist.py", line 972, in run_command
[00:03:08]     cmd_obj.run()
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\install.py", line 67, in run
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\install.py", line 117, in do_egg_install
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\easy_install.py", line 389, in run
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\easy_install.py", line 619, in easy_install
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\co
[00:03:08] mmand\easy_install.py", line 670, in install_item
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\easy_install.py", line 718, in process_distribution
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\pkg_resources\__init__.py", line 836, in resolve
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\pkg_resources\__init__.py", line 1081, in best_match
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\pkg_resources\__init__.py", line 1093, in obtain
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\easy_install.py", line 638, in easy_install
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\easy_install.py", line 668, in install_item
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\easy_install.py", line 851, in install_eggs
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setup
[00:03:08] tools-18.4-py2.7.egg\setuptools\command\easy_install.py", line 1079, in build_and_install
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\easy_install.py", line 1065, in run_setup
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\sandbox.py", line 240, in run_setup
[00:03:08]   File "C:\Python27-conda32\lib\contextlib.py", line 35, in __exit__
[00:03:08]     self.gen.throw(type, value, traceback)
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\sandbox.py", line 193, in setup_context
[00:03:08]   File "C:\Python27-conda32\lib\contextlib.py", line 35, in __exit__
[00:03:08]     self.gen.throw(type, value, traceback)
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\sandbox.py", line 164, in save_modules
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\sandbox.py", line 139, in resume
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\sand
[00:03:08] box.py", line 152, in save_modules
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\sandbox.py", line 193, in setup_context
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\sandbox.py", line 237, in run_setup
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\sandbox.py", line 267, in run
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\sandbox.py", line 236, in runner
[00:03:08]   File "C:\Python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\sandbox.py", line 46, in _execfile
[00:03:08]   File "c:\users\appveyor\appdata\local\temp\1\easy_install-q09dn_\autograd-1.1.1\setup.py", line 62, in <module>
[00:03:08]     
[00:03:08]   File "C:\Python27-conda32\lib\distutils\core.py", line 151, in setup
[00:03:08]     dist.run_commands()
[00:03:08]   File "C:\Python27-conda32\lib\distutils\dist.py", line 953, in run_commands
[00:03:08]     self.run_command(cmd)
[00:03:08]   File "C:\Python27-conda32\lib\distutils\dist.py", line 972, in run_c
[00:03:08] ommand
[00:03:08]     cmd_obj.run()
[00:03:08]   File "c:\python2
[00:03:08] 7-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\bdist_egg.py", line 151, in run
[00:03:08]   File "C:\Python27-conda32\lib\distutils\cmd.py", line 326, in run_command
[00:03:08]     self.distribution.run_command(command)
[00:03:08]   File "C:\Python27-conda32\lib\distutils\dist.py", line 972, in run_command
[00:03:08]     cmd_obj.run()
[00:03:08]   File "c:\python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\egg_info.py", line 180, in run
[00:03:08]   File "c:\python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\egg_info.py", line 207, in find_sources
[00:03:08]   File "c:\python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\egg_info.py", line 291, in run
[00:03:08]   File "c:\python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\egg_info.py", line 320, in add_defaults
[00:03:08]   File "c:\python27-conda32\lib\site-packages\setuptools-18.4-py2.7.egg\setuptools\command\sdist.py", line 130, in add_defaults
[00:03:08]   File "C:\Python27-conda32\lib\distutils\cmd.py", line 312, 
[00:03:08] in get_finalized_command
[00:03:08]     cmd_obj.ensure_finalized()
[00:03:08]   File "C:\Python27-conda32\lib\distutils\cmd.py", line 109, in ensure_finalized
[00:03:08]     self.finalize_options()
[00:03:08]   File "c:\users\appveyor\appdata\local\temp\1\easy_install-q09dn_\autograd-1.1.1\setup.py", line 19, in finalize_options
[00:03:08]     version=versioneer.get_version(),
[00:03:08] AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
[00:03:08] Command exited with code 1
```

**Comment by mattjj** [comment]
Oh interesting... so I got that `__NUMPY_SETUP__` bit [from stackoverflow](http://stackoverflow.com/q/19919905), and it's just meant to handle the case where someone doesn't already have numpy installed (so pip installs it as a dependency, yet we need to grab its include files if we do any compilation). It's only useful in that corner case where you don't already have numpy.

I don't understand why it's trying to re-install numpy, so that's still a mystery. But I think I understand the error!

It looks like one should use `__builtin__` there and not `__builtins__`, since [one is sometimes a dict while the other is always a module](http://stackoverflow.com/a/1184036). Can you try changing that line to use the name `__builtin__` and see if it works?

**Comment by mattjj** [comment]
Oh man, by tweaking `__builtin__` I broke the build on the master branch. Whoops. Let me know if you figure out the right thing to do here.

**Comment by richardotis** [comment]
@mattjj I tweaked the build script to use pip instead and it seems to be working without any changes on your end. Now I'm having an issue with tests failing but I won't know the cause until I fix some issues with stderr and nosetests on AppVeyor.

**Comment by richardotis** [comment]
I'm waiting to hear back from AppVeyor about getting nose to behave correctly since some tests appear to be failing, but the output of the test isn't showing, making it impossible to debug. Once I address that issue I'll merge.

**Comment by richardotis** [comment]
The good news is I have it building properly on AppVeyor and also fixed a bug on Windows. For completeness I'm going to try to get Travis building pycalphad on OSX as well, so that way I have full coverage. I can't predict floating point issues so this seems like a good idea.

**Pull request merged**
